- components/network/id.ftl
- components/network/setup.ftl
- components/network/state.ftl
- masterData.ftl
- services/microsoft.network/id.ftl
- services/microsoft.network/resource.ftl
Will be separating future services/components into their own PRs, so that component design/testing does not hold back the merge of new Services.
Service includes the following Resource definitions that will allow the creation of the standard Django Stack Network components listed in #25 :
- [virtualNetworks](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-02-01/virtualnetworks)
- [subnets](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-02-01/virtualnetworks/subnets)
- [networkSecurityGroups](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-02-01/networksecuritygroups)
- [routeTables](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-02-01/routetables)
also includes the following sub-Resource …
> initial implimentation of microsoft.network Service 

- components/s3/setup.ftl
- deploymentframeworks/arm/output.ftl
- services/microsoft.managedidentity/resource.ftl
- services/microsoft.network/resource.ftl
- services/microsoft.storage/resource.ftl
- services/resource.ftl
This PR extends the resourceProfile functionality established in #33. It adds the idea of resource conditions, which will allow for manipulation of the resource object in a number of places. 
An example that has been implemented in this PR is where a resource requires a lowercase name. Storage Accounts in azure have strict naming requirements. Here we can list those requirements in an array at the profile level, then the resource is created as normal without having to factor in extra processing for the lower case name . Immediately before either the resource is created (or during the referencing of its attributes), the conditions are all processed on the resource, then it is added to the output json. In this way, we can easily re-use similar requirements for future resources by including …
> Feat resource profile conditions

- deploymentframeworks/arm/output.ftl
This PR enables the use of the Zones attribute, which will soon be utilised by the Bastion component
> Allow Zones attribute on armResource.

- services/resource.ftl
Function to format an Azure Service Endpoint address. Typically used for pre-pending a resourceName to the endpoint suffix but the extensions attribute allows for adding additional parts to the path -  ex: dfs storage endpoints.
To be used by codeontap/gen3-azure#26
> Get Azure Service Endpoint function

- components/gateway/id.ftl
- components/gateway/setup.ftl
- components/gateway/state.ftl
- components/network/state.ftl
- inputsources/shared/masterdata.ftl
- services/microsoft.network/resource.ftl
This PR implements & closes #26 
The Gateway component in its current MVP state (without privateEndpoints but with publicEndpoints) does not deploy any resources. As discussed in #26 many of the standard resources that would make up a Gateway component within Azure are handled behind the scenes by MSFT. Additionally, there were a number of requirements for some resources to be made alongside Subnet's within the Network component, so they have been migrated to that instead.
As such, the Gateway component currently stands as both a flag to alert CodeOnTap that the Gateway has been accounted for and also as the skeleton state/setup files that will be required for the later implementation of privateEndpoints.
Example generated template:
```
{
"$schema": …
```
> Feat component gateway

- inputsources/composite/stackoutput.ftl
draft of ARM stack output processing once codeontap/gen3#1108 is implemented
Example of template outputs for reference:
```
{
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"parameters": {},
"variables": {},
"resources": [
...
],
"outputs": {
"storageXmgmtXbaseline": {
"type": "string",
"value": "[resourceId('Microsoft.Storage/storageAccounts', 'storage6fj1615ggo')]"
},
"storageXmgmtXbaselineXname": {
"type": "string",
"value": "storage6fj1615ggo"
},
"storageXmgmtXbaselineXurl": {
"type": "string",
"value": "[reference(resourceId('Microsoft.Storage/storageAccounts', 'storage6fj1615ggo'), '2019-04-01', 'Full').properties.primaryEndpoints.blob]"
}
}
}
```
This would then create a Composite Stack Output file that …
> ARM Stack Output Processing in Engine

- inputsources/composite/stackoutput.ftl
This PR introduces a minor fix to take the stack output names that Azure requires which use camelCase on their keys, to Capitalised keys that are mandatory for CodeOnTap. For example a Region output is mandatory, however Azure will output that as "region".
> Fix az stackoutput

- components/baseline/setup.ftl
- components/baseline/state.ftl
- inputsources/shared/masterdata.ftl
- services/microsoft.keyvault/id.ftl
- utility.sh
Baseline keyvault is currently not allowing access from the Azure administrator's group or anyone without changes beyond the scope of the baseline component. This isn't ideal as it prevents codeontap when run to upload/generate any private keys into the vault. This PR implements IPAddressGroups for SSH keys, which defaults to "_global". The Azure implementation of this will then effectively say "all networks can access this keyvault" (permission restrictions remain). This allows the baseline component to run its epilogue scripts and generate applicable keys.
Speaking of keys, this PR also refactors the way the keys are generated. Azure CLI can generate RSA keys directly into Keyvault and doing so means much a much more simplistic epilogue script implementation. 
Due to these significant …
> Refactor of Baseline Component Keyvault implementation

- components/baseline/state.ftl
- components/spa/id.ftl
- components/spa/setup.ftl
- components/spa/state.ftl
- services/microsoft.network.frontdoor/resource.ftl
- services/microsoft.storage/resource.ftl
- utility.sh
Contributes to #59
Contributes to #60  
Establishes the foundations for an SPA component.
Unlike a typical component, the SPA does not generate a template, it instead creates prologue/epilogue shell scripts that when run will stage and sync a Single Paged Application into an Azure Blob Store. This PR implements this.
The final SPA component will address the SPA content that is stored on a CDN - In Azure's case that is the "FrontDoor". The CDN needs to be notified to store the new content and purge the old cached content. This PR does not include this yet as the CDN content is remains in development and as such it does not close the original ticket. Once both CDN and SPA components exist and work together I will close off both PRs.
Example prologue script:
``` sh
#!/usr/bin/env bash …
```
> created spa component sans cdn interactions.

- deploymentframeworks/arm/output.ftl
- services/microsoft.compute/resource.ftl
- services/microsoft.insights/resource.ftl
- services/microsoft.keyvault/resource.ftl
- services/microsoft.managedidentity/resource.ftl
- services/microsoft.resources/resource.ftl
- services/microsoft.storage/resource.ftl
Output mappings have changed since their first creation in the Azure provider. This refactor standardises them across all Services, and tidies up the ```@armResource``` for readability.
This PR also addresses an issue where the only outputs being created in a given template were the ones every template receives.
> Refactor Output Mappings

- deploymentframeworks/arm/output.ftl
- services/microsoft.compute/resource.ftl
- services/microsoft.insights/resource.ftl
- services/microsoft.keyvault/resource.ftl
- services/microsoft.managedidentity/resource.ftl
- services/microsoft.network.applicationgateways/resource.ftl
- services/microsoft.network.frontdoor/resource.ftl
- services/microsoft.network/resource.ftl
- services/microsoft.resources/resource.ftl
- services/microsoft.storage/resource.ftl
- services/microsoft.web/resource.ftl
- services/resource.ftl
When implementing a new resource in the Azure Provider, two related macros are always required - ```addResourceProfile``` (azure-specific macro) and ```addOutputMappings``` (codeontap macro). The output Mappings define an individual resources outputs when instantiated, and lends itself quite well to being a part of the profile. This PR incorporates the outputMappings as a mandatory attribute of the Resource Profile, reducing the number of macro calls and duplication.
In order to continue to support cross-provider outputs (through ```getOutputMappings```, macro ```addResourceProfile``` will still call ```addOutputMappings``` behind the scenes, but when adding a resource to a template through ```armResource``` we will make reference to the resource profile because its always going to be …
> Refactor - OutputMappings into Resource Profile

- inputsources/shared/masterdata.ftl
Azure has a number of different StorageAccount [types that can be created](https://docs.microsoft.com/en-gb/azure/storage/common/storage-account-overview). Typically they recommend the generic types of v1 (legacy) or v2, however if you know exactly what you are looking for then you can get some performance enhancements for specific use-cases by specifying specific types like BlobStorage or FileStorage. When you do this the other types are not enabled on the storage account.
This PR makes the "default" storageProfile for Azure use the StorageV2 type, which will allow storage of all kinds by default. This will be useful for the Baseline component, to ensure the maximum coverage of storage scenarios.
> Default StorageAccount Kind Update

- components/baseline/state.ftl
- components/sqs/id.ftl
- components/sqs/setup.ftl
- components/sqs/state.ftl
- utility.sh
Closes #64 
Implements the MVP for the SQS Component.
Note that there is currently no Azure Resource for deploying a Queue resource to the Azure Storage Account. This template generates a prologue script that will use the CLI to accomplish the same goal, with the aim to replace this once MSFT implement a queue resource.
> Component - SQS

- components/baseline/state.ftl
- components/gateway/state.ftl
- components/network/state.ftl
- components/s3/state.ftl
- components/spa/state.ftl
Contributes to codeontap/gen3#1215
As per the associated gen3 PR, this attribute is no longer supported and has been removed.
@ml019 please merge along with your PR.
> Refactor - Remove baseState from State macros

- components/sqs/state.ftl
SQS component was being developed whilst the baseState changes of codeontap/gen3#1215 was being reviewed. Had to exist for development but now should be removed.
> Refactor - SQS BaseState

- components/baseline/setup.ftl
- components/s3/setup.ftl
- components/s3/state.ftl
- services/microsoft.storage/resource.ftl
- services/resource.ftl
Contributes to and Closes #65 
More a refactor as this component was the first created, though with less explicit requirements.
This refactor revisits the naming of storage account, container and blob store resources to ensure that their naming conditions are all met. It also introduces a new resourceProfile attribute - ```max_name_length```. This attribute is read during the processing of the naming condition "max_length" (also new) and abbreviates the name accordingly.
Finally the networkACL for this component defaults to Allow, to allow for administration of the storageAccount. As the component evolves this will become further locked down, however for now it will rely upon authentication.
> Component - S3

- components/network/setup.ftl
- inputsources/shared/masterdata.ftl
- services/microsoft.network/resource.ftl
Azure has some[ very specific requirements](https://docs.microsoft.com/en-us/azure/application-gateway/configuration-overview#network-security-groups-on-the-application-gateway-subnet) for Application Gateway resources - they require their own subnet and the NSG's associated with that subnet have their own requirements - they require open access between the GatewayManager service tag and the subnet as well as the AzureLoadBalancer service tag.
Currently, there are known problems with the GatewayManager service tag being used within NSG rule definitions - it simply wont work. Rules using this service tag will block access. Application Gateway's validate this access before deployment so their deployment will fail if they use this service tag currently.
The only known work around for the …
> ELB into Separate Network Security Group

- services/microsoft.authorization/id.ftl
- services/microsoft.authorization/policy.ftl
- services/microsoft.authorization/resource.ftl
- services/service.ftl
This PR introduces the Service - Microsoft.Authorization. It includes
* Macro for the creation of a custom role definition
* macro for the creation of a new role assignment
* new global variable `userRoles` which is used as a library for looking up "BuiltInRoles" (microsoft defined roles). This saves us from looking up their Id's on the fly.
* new `function getRoleReference()` for making use of the `userRoles` library to construct a reference to them.
Note: CustomRule references should continue to be obtained from either their outputMapping (other templates) or `occurrence.State.Resources[<resource>].Reference` (preferably through variables to that effect) for current-template.
> Service - Authorization

- components/baseline/setup.ftl
- services/microsoft.storage/resource.ftl
SoftDelete is a property of KeyVault that allows the recovery of deleted items. In order to provision an Application Gateway resource with a certificate stored in KeyVault, the Vault must have SoftDelete enabled.
This PR incorporates that change into the baseline component.
Also fixes an incorrect call to the `attributeifTrue()` function.
> KeyVault SoftDelete in Baseline

- deploymentframeworks/arm/output.ftl
- services/resource.ftl
By default in the Azure provider currently the `getReferene()` function, if returning a reference() ARM function call, will return a full Resource. This PR updates this to be optional, so you can retrieve just the properties, or the entire object.
Some properties interestingly don't return when "Full" is specified - importantly this includes the "principalId" of a User Assigned Identity as is used in the lb component.
> Fix - GetReference

- azure/components/network/state.ftl
Azure provider PR that addresses same as hamlet-io/engine-plugin-aws#25 - don't assume that this object exists.
Bug preventing network component or anything that links to it from generating as it doesn't exist by default.
Local template generation.
> dont assume segment operations exists

- azure/components/bastion/setup.ftl
- azure/inputsources/shared/masterdata.ftl
- azure/references/SkuProfile/id.ftl
- azure/references/SkuProfile/reference.ftl
- azure/references/VMImageProfile/id.ftl
- azure/references/VMImageProfile/reference.ftl
- azure/references/reference.ftl
- Moves the VMImageProfiles reference data into azure plugin provider.
- Refactors structure into correct alignment with other profile reference data types.
- Refactors "bastion" component to make use of new structure.
- Added some missing pieces for getSkuProfiles that I appear to have neglected to include in previous PR's but are definitely required to work.
- Split content between two files per reference type for clarity.
#66 will require VM Images, and #129 established working correct structure of reference data in plugins.
The move from the shared provider to the plugin was due to it being previously introduced at a time that reference data wasn't being dynamically loaded by plugins, which is no longer the case.
- skuProfiles has previously been tested - not sure why it didn't get …
> Refactor - VM Image Profiles + Move to Plugin

- azure/utility.sh
Updates utilities.sh to:
- specify an auth-mode for storage account sync functions
- update several functions with quieter modes that will still show errors.
General noise reduction in output during deployment. An auth-mode of login will use the currently logged in account for the file sync, which is already a requirement for deployment.
Deployed successfully.
> Feature - SPA Auth Mode and Quiet

- azure/components/apigateway/state.ftl
- azure/components/userpool/setup.ftl
- azure/components/userpool/state.ftl
Amends the Userpool outputs to include the ClientId and the ObjectId, which are used by different hamlet components.
Includes a refactor of the APIGateway reference to the ObjectId to make it clearer which attribute is which.
An application registration - the result of a Userpool deployment unit using the AAD engine type  in Azure - should output both the ClientId (also known as App Id) which is required by application deployments as well as the ObjectId, which is how an API Gateway references the registration. Currently its only outputting the ObjectId.
Local template generation and deployment
> Feature - Userpool Output Client + Object Ids

- azure/components/computecluster/setup.ftl
- azure/components/s3/state.ftl
Updates the compute cluster's package name that it expects. Sets a default in the baseline storage Account, and overrides if there is a linked s3 component.
Current name was based on productName, which was very generic and not much use in multi-package solutions.
Templates generated and deployed.
> Refactor - ComputeCluster Package Name

- azure/components/s3/setup.ftl
Updated ACL's for S3 component to match baseline storage account setup.
Current setup does not allow the author to view the contents of a storage account after its created.
Combination of testing in the portal and comparison with baseline template configuration which uses the same resources.
> Fix - Update S3 Access Rules

- azure/components/computecluster/setup.ftl
- azure/services/microsoft.compute/resource.ftl
Corrects a problem gathering ScaleSet Extension configuration when the last Bootstrap Profile loaded doesn't have a publisher/type/handler configured.
Bug was exposed after adding a new Bootstrap which did not have these attributes.
Local template generation and subsequent deployment.
> fixed publisher/type/handler for extension config

- azure/components/computecluster/setup.ftl
- azure/services/microsoft.compute/resource.ftl
Timestamp must be passed as an int, to later re-read it and compare with current time.
Pass the timestamp value as an integer to the template. 
- Includes a refactor to move the timestamp generation and value into a bool on the resource to ensure its always passed correctly.
Whilst deploying successfully initially, passing the timestamp as a string prevents Azure from comparing the string with a timestamp in another deployment (it attempts to compare integers to see if one is later than the other). This prevents most changes to the resource from being successful even when unrelated.
> Fix - ComputeCluster Timestamp Bug

- azure/components/computecluster/setup.ftl
- azure/inputsources/shared/masterdata.ftl
Merged the "Script" and "CommandToExecute" properties of the bootstrap process into the latter.
Turns out you can't use both together and there will usually be a need to perform at least the base64 encoding on a script before executing it (a requirement for the "script" parameter". Deployment was always successful together but issues would appear later when trying to modify the resource.
> Fix - ComputeCluster InitScript

- azure/components/spa/setup.ftl
Fixed SPA path from starting with '/'
This would cause a double-slash when the path was merged with the container name $web, causing the path to create an empty directory called <no-name> which would then break the site.
> fix: :bug: forwarding path not to start with /

- azure/components/gateway/setup.ftl
- azure/components/gateway/state.ftl
- azure/components/network/setup.ftl
- azure/inputsources/shared/masterdata.ftl
Implements the rename of vpcendpoint to private service as part of https://github.com/hamlet-io/engine/pull/1335 
Vendor agnostic naming of the gateway engine type
Tested on local deployment
> refactor(gateway): rename vpcendpoint to privateservice

- azure/inputsources/shared/masterdata.ftl
Minor refactor to remove the console only option from the segment/bastion masterdata. This option is not longer supported and shouldn't be used
This should be more a bastion component specific option rather than a master data controlled thing 
Tested locally
> refactor: remove console only from bastion masterdata

- azure/deploymentframeworks/arm/output.ftl
- azure/services/microsoft.apimanagement/resource.ftl
- azure/services/microsoft.network.frontdoor/resource.ftl
- azure/services/resource.ftl
Update Resource Profiles to include a setting for Global resources.
Global resources should use the "global" region, overriding any other region defined elsewhere.
Local template generation on the CDN Component - FrontDoor was thus assigned a location of "global" whilst other resources did not.
> Feat global resource config

- azure/components/cdn/state.ftl
Use the segment seed to make frontdoor names globally unique
The name of a frontdoor is used to determine the base DNS name for the frontdoor. As a result of this the name must be globally unique across all azure customers. 
Tested locally
> fix(cdn): ensure frontdoor names are unique globally

- azure/components/lambda/state.ftl
- azure/services/microsoft.web/resource.ftl
- Update `Sites` resource (web app, including lambdas) to use the `formatAzureResourceName()` function.
- Include naming conditions on resource - `max_length` (60) and `globally_unique`
Both naming conventions are enforced by Azure on this resource.
Local template generation.
Breaking Change : This will require re-deployment of Lambda's that have already been deployed.
> Fix - Lambda Naming

- azure/components/apigateway/setup.ftl
fix to API gateway to only through an exception on the api definition not existing in the template subset
There was an error that the definition file couldn't be found during the generation of the script which builds the definition file
Tested locally
> fix(apigateway): Definition failing before pulled

- azure/components/apigateway/setup.ftl
- azure/services/microsoft.apimanagement/resource.ftl
Move the parameter generation out of the apigateway resource and into it's own section in the setup routine
This ensures we are only calling the appropriate macros for the given subset that is being generated. Currently each of these steps are run for all subsets so if there is an issue its difficult to see when its happened
Tested locally
> fix(apigateway): fix subset scopes for apigateway generation

- azure/components/baseline/state.ftl
- azure/components/s3/state.ftl
- azure/services/microsoft.storage/resource.ftl
- Swap the ordering of the naming for storage accounts to make sure that only alphanumeric characters are used. 
- Update the naming of storage accounts so that we get the most out of the limited characters that we have available 
Fix an issue with storage account deployments and to make it easier to determine the storage account you need
Tested locally
> fix(storage): fix storage account naming

- azure/services/resource.ftl
Adds a `scope` attribute to azureResourceProfiles, to define the default deployment scope for a given resource. 
Contributes to #196 
Adds the capability but as yet unused anywhere.
> feat(resources): incorporate scope into azureResourceProfiles

- azure/components/adaptor/setup.ftl
- azure/components/apigateway/setup.ftl
- azure/components/baseline/setup.ftl
- azure/components/bastion/setup.ftl
- azure/components/cdn/setup.ftl
- azure/components/computecluster/setup.ftl
- azure/components/containerhost/setup.ftl
- azure/components/db/setup.ftl
- azure/components/gateway/setup.ftl
- azure/components/lambda/setup.ftl
- azure/components/lb/setup.ftl
- azure/components/network/setup.ftl
- azure/components/s3/setup.ftl
- azure/components/spa/setup.ftl
- azure/components/sqs/setup.ftl
- azure/components/userpool/setup.ftl
- azure/deploymentframeworks/arm/output.ftl
- test/run_azure_template_tests.sh
Aligns the Azure component setup macros with the new entrances lookup
structure as part of the components flow introduced in
https://github.com/hamlet-io/engine/pull/1407
BREAKING CHANGE: setup marco names do not support the current naming
format
Allows for dynamically loaded outputs to use a standard flow process through hamlet
Tested locally
> refactor: setup macro support for entrances

- azure/components/adaptor/setup.ftl
- azure/components/apigateway/setup.ftl
- azure/components/cdn/setup.ftl
- azure/components/lambda/setup.ftl
- azure/components/spa/setup.ftl
- azuretest/modules/adaptor/module.ftl
- azuretest/modules/lambda/module.ftl
Azure provider implementation of https://github.com/hamlet-io/engine/pull/1494 
Migrates all components which support fragments over to extensions
processing. 
This allows for extensions to be defined as part of plugins
and also allows for multiple extensions to be used on a component
tested locally
> feat: migrate from fragments to extensions

- azure/services/microsoft.keyvault/id.ftl
Remove the definition of the SECRET_ATTRIBUTE_TYPE from the azure provider as its now available in the SHARED_PROVIDER ( https://github.com/hamlet-io/engine/pull/1485 ) 
Allows for anyone to have a secret
Tested locally
> refactor: move secret attribute to shared

- azure/deploymentframeworks/arm/output.ftl
- azure/services/resource.ftl
This commit updates getReference() with a check to see if its working
with a pseudo resource profile. If it is, it calls getExistingReference instead of incorrectly constructing an ARM `[referenceId()]` function.
The baseline component uses a pseudo resource profile to represent the "seed". If it hasn't been deployed yet (in the prologue) but the template pass runs, `getReference()` incorrectly formats an ARM function. This then becomes part of the name of the KeyVault, which then becomes a part of the name for a KeyVault Secret, and its all a huge (invalid) mess.
```bash
{"error":{"code":"InvalidTemplate","message":"Deployment template language expression evaluation failed: 'Unable to parse language expression 'resourceId('Microsoft.KeyVault/vaults', 'vault-[resourceId('pseudo', '')]')': …
```
> Bugfix - getReference and Pseudo Resource Profiles

- Jenkinsfile
- azure/components/baseline/state.ftl
- azure/components/spa/setup.ftl
- azure/deploymentframeworks/arm/output.ftl
- azure/inputsources/mock/blueprint.ftl
- azure/inputsources/mock/commandlineoption.ftl
- azure/inputsources/mock/stackoutput.ftl
- azure/references/SkuProfile/reference.ftl
- azure/references/VMImageProfile/reference.ftl
- azuretest/modules/adaptor/module.ftl
- azuretest/modules/apigateway/module.ftl
- azuretest/modules/baseline/module.ftl
- azuretest/modules/bastion/module.ftl
- azuretest/modules/cdn/module.ftl
- azuretest/modules/computecluster/module.ftl
- azuretest/modules/lambda/module.ftl
- azuretest/modules/lb/module.ftl
- azuretest/modules/network/module.ftl
- azuretest/modules/s3/module.ftl
- azuretest/modules/spa/module.ftl
- azuretest/provider.ftl
* corrects the way the segmentSeed is sought/resolved in c403198 and simmillarly for outputs in 609ac54
* corrects relative scope issues when mocking in f0b95dd (Closes #216)
* corrects an early loading of provider-specific referenceData in 3c3db03 + e6ea316
* fixes a call to invokeExtension() in the `spa` component that passes an invalid variable in 782ebd1
* standardises mock values in the testing provider to keep values aligned in 164d969
* Re-enables CI testing
* Corrects A number of minor fixes that the testing picked up
Addresses and Closes #216 
Tests now pass locally with:
```bash
./test/run_azure_template_tests.sh
```
> Fix - Azure Provider Tests

- azure/inputsources/mock/commandlineoption.ftl
- azuretest/provider.ftl
To ensure consistency for data types when using mocked input sources,
the Azure provider defines a number of global variables formatted
appropriately for that type.
These types are currently defined mostly in the azuretest provider,
as testing is the most-common use-case for using the mock input
source.
This poses a problem for new entrances that may make use of the
mock inputsource, as they will require both azure and azuretest
providers to be loaded.
This change moves the definitions for Mock types into the azure
provider, so they can be used by other entrances for non-testing
capabilities. The result is that in order to use mock, you only
have to load the azure provider, but to perform tests, you must
load both (already a requirement).
New entrances in development that use the mock …
> fix: move mock input types into azure provider

- azure/inputseeders/azure/id.ftl
- azure/inputseeders/azure/masterdata.json
- azure/inputseeders/azure/regions.json
- azure/inputseeders/inputseeder.ftl
Add basic input seeder support for azure.
This change introduces the seeder support needed to use the azure plugin with the refactored input source processing.
It doesn't replace any existing processing in order to stagger the changes needed to transition to the new input approach.
Local template generation
> feat: input seeders

- azure/deploymentframeworks/arm/output.ftl
- azure/inputsources/composite/stackoutput.ftl
- Adds a missing "ResourceGroup" output to the standard provider outputs
- Moves the "ResourceGroup" naming convention from the Executor into the Engine
The current naming convention for the ResourceGroup is established at template deployment time within the Executor, and its value is a concatenation of various environment variable string values. 
All of the information is available however in the Engine which is where the outputs are assigned. It makes sense for the Engine to be responsible for this assignment, rather than the executor. It is also provider-specific, so moving it out of the Executor is ideal.
Template generation and deployment
> Fix - Azure ResourceGroup Outputs

- azure/utility.sh
Fix to check for the log level configured instead of if the log level is present
This ensures that even on a defaulted log level that the behaviour is as
expected
Tested locally
> fix: debug log output on util commands

- azure/inputseeders/azure/id.ftl
Ensure Azure specific outputs are appended to any that are already in the state.
With the shared provider looking after pseudo stacks, their content will already be in the state when the Azure normaliser runs.
Local template generation
> fix: pseudo stacks

- azure/components/spa/id.ftl
- azure/components/spa/setup.ftl
- azure/components/spa/state.ftl
- azure/services/microsoft.storage/resource.ftl
- Breaking change (fix or feature that would cause existing functionality to change)
BREAKING CHANGE: As per #246, only 1 SPA per Solution is currently possible in the
Azure provider. This is due to the SPA initially deploying content
into the OpsData databucket. However Azure has some unique req. for
hosting static website content, such as a specific container name of
$web being necessary. As there can only be one container with such a
name per Storage Account, this is a problem.
This refactor implements a unique storage account per SPA deployment-
unit.
Additionally, this removes a previous limitation of SPA's that there
must be at least one existing CDN Route in order to deploy. Such a
requirement posed a chicken-and-egg problem where the CDN Route couldn't
exist without the SPA, and …
> refactor!: SPA to have independant storage account

- azure/inputseeders/azure/id.ftl
Ensure masterdata does not trigger layer attribute failures during intermediate passes of config pipeline processing.
Testing of cmdb processing showed layer processing was incorrectly reporting missing attributes.
Local template generation. The test suite has also been run
- Engine - https://github.com/hamlet-io/engine/pull/1663
- None
- None
> fix: dynamic cmdb loading

- azure/components/apigateway/state.ftl
- azure/components/baseline/setup.ftl
- azure/components/cdn/state.ftl
- azure/components/lb/setup.ftl
- azure/components/lb/state.ftl
- azure/components/s3/setup.ftl
- Breaking change (fix or feature that would cause existing functionality to change)
Remove all usage of the `segmentQualifier` global variable.
With input pipeline processing performing qualification, there is no longer a need for component code to explicitly handle qualification.
BREAKING CHANGE: Move any LB port specific certificate configuration to the affected port configuration rather than qualifying it at the LB level.
Local template generation
- https://github.com/hamlet-io/engine/pull/1695
- None
- Refactor solutions to place port specific certificate configuration on load balancers on the individual ports rather than using port qualifiers on the LB level certificate object.
> refactor!: remove use of segmentQualifier

- azure/components/lb/setup.ftl
- azure/components/lb/state.ftl
Moves the FQDN and certificateId lookup process into the state function instead of doing it in setup as well
Removes duplication and allows for complex certificate handling to be managed in state
- https://github.com/hamlet-io/engine/pull/1748
- None
- None
> refactor: lb fqdn handling

- azure/components/bastion/setup.ftl
- azure/components/bastion/state.ftl
- azure/components/computecluster/setup.ftl
- azure/components/computecluster/state.ftl
- azure/components/network/setup.ftl
- azure/components/network/state.ftl
- azure/inputseeders/azure/masterdata.json
- azure/services/microsoft.compute/resource.ftl
- azure/services/microsoft.network/resource.ftl
- Breaking change (fix or feature that would cause existing functionality to change)
- Adds support for named IP Address Groups when creating network security rules - This allows for use of the Azure builtin network prefixes
- Removes creation of explicit elb network NSG and instead replaces it with a generic ACL which can be applied on any subnet
- Moves network acl creation into the subcomponent and treats the subnet level NSG as the hamlet network ACL
- Moves subnet creation into the vNet as sub resources of the vNet instead of top level resources
- Adds support for a _none …
> refactor(network)!: refactor network setup process

- azure/components/directory/id.ftl
- azure/components/directory/setup.ftl
- azure/components/directory/state.ftl
- azure/inputseeders/azure/masterdata.json
- azure/references/SkuProfile/id.ftl
- azure/services/microsoft.aad/id.ftl
- azure/services/microsoft.aad/resource.ftl
- azure/services/service.ftl
- Adds support for using the directory component to provision a  Azure AD Directory Services instance
- Adds additional subnet level NSGs which add the required rules to have a private AD instance with support from the Azure named prefixes
This allows for using Azure Active Directory groups and users to authenticate with services which support traditional AD services
Tested on local deployment
- https://github.com/hamlet-io/engine-plugin-azure/pull/283
- None
- None
> feat(directory): Azure AD Directory Services

- azure/components/lambda/setup.ftl
- azuretest/modules/lambda/module.ftl
- Use the subOccurrence properties to determine the build settings instead of the parent
Build settings were failing on lookup
Tested locally and with test suite
- None
- None
- None
> fix(lambda): build settings lookup

- .github/workflows/release.yml
- Removes the junit reporter to reduce false error reporting due to PR permissions
The reporting tool was raising warnings on PRs as PRs only have write access to repos and can't create new checks that are required by the reporter. 
It also isn't too useful for hamlets testing approach which tests outputs rather than the code itsself
Will be tested as part of PR
- None
- None
- None
> cd: remove junit reporting

- azure/components/network/setup.ftl
- azure/components/network/state.ftl
- azure/inputseeders/azure/id.ftl
- azure/services/microsoft.authorization/policy.ftl
- azure/services/resource.ftl
- azuretest/extensions/azure_adaptorbase/extension.ftl
- azuretest/inputseeders/azuretest/id.ftl
- azuretest/modules/adaptor/module.ftl
- azuretest/modules/apigateway/module.ftl
- azuretest/modules/baseline/module.ftl
- azuretest/modules/bastion/module.ftl
- azuretest/modules/cdn/module.ftl
- azuretest/modules/computecluster/module.ftl
- azuretest/modules/db/module.ftl
- azuretest/modules/gateway/module.ftl
- azuretest/modules/lambda/module.ftl
- azuretest/modules/lb/module.ftl
- azuretest/modules/network/module.ftl
- azuretest/modules/s3/module.ftl
- azuretest/modules/segment/module.ftl
- azuretest/modules/spa/module.ftl
- azuretest/modules/sqs/module.ftl
- azuretest/modules/userpool/module.ftl
- Removes the mock output service to allow for referencing between resources to behave as intended
- Consolidate deployment units to components to reduce testing time
- Align configuration with latest configuration options
The intention with this change is to make sure that template content is generated as expected and doesn't rely on faked reference values and instead assumes that resources aren't all deployed
Tested locally
- None
- None
- None
> refactor: remove mock output service from testing

- azure/services/microsoft.network/resource.ftl
- Creates standard definitions of the vpn ipsec ciphers used for virtual network gateways based on group number based standard
When configuring the VPN ipsec cipher suite using just the group number would only map to the cipher spec and didn't include the PFS configuration. To standardise the approach and use PFS as a standard security standard we now map the number group numbers to PFS and cipher suite groups
Tested locally and on VPN between AWS and Azure. 
- None
- None
- None
> feat(network): manage vpn cipher configuration

- azure/components/adaptor/setup.ftl
- azure/components/computecluster/setup.ftl
- azure/services/microsoft.storage/resource.ftl
Replace/remove getRegistryPrefix and getRegistryEndPoint calls
It would be useful if someone that understands the motivation behind the change in location identification could check this is consistent with the reason for the removal of getRegistryPrefix and getRegistryEndPoint
Current failures in Azure plugin causes tram and train hamlet builds to fail
Locally run test suite to ensure AWS tram and train can be built
- None
- None
- None
> fix: remove use of getRegistryPrefix and EndPoint

- azure/components/computecluster/setup.ftl
- Removes the bootstraps global variable lookup and replaces it with a locally defined reference to the boostraps
Generation of computercluster templates failing
Tested with test suite
- None
- None
- None
> fix(computecluster): bootstraps lookup from global
