hamlet-io/engine-plugin-azure

.gitignore
dev/deploy.ps1
dev/parameters.json
dev/post-deploy.sh
dev/template.json

Initial commit of template for basic VM /w Object Storage and system-managed identity. #4

initial commit

---

.gitignore
dev/README.md
dev/epic0/template.json
dev/epic2/README.md
dev/epic2/manageDeployment.sh
dev/epic2/templates/seg-iam-mswdev-eastus-template.json
dev/epic2/templates/seg-network-mswdev-eastus-template.json
dev/epic2/templates/seg-rbac-mswdev-eastus-template.json
dev/epic2/templates/seg-storage-mswdev-eastus-template.json
dev/epic2/templates/seg-virtualmachines-mswdev-eastus-template.json

epic2 - deploying existing ARM templates using CodeOnTap functionality. Work is performed by the manageDeployment.sh script, which is based on the cf provider-specific manageStack.sh.

Feat deploy

---

deploymentframeworks/arm/output.ftl
services/resource.ftl

A couple of minor fixes 
- Support for the new StackOutput lookup introduced in https://github.com/codeontap/gen3/pull/1007 
- Add Azure specific genplan mappings 
- Add azure resource output type

<fix> getExistingReference for new stackoutput

---

deploymentframeworks/arm/output.ftl

Minor fix to align with https://github.com/codeontap/gen3/pull/1019

<fix> Output initilsation should be run before calling output

---

services/microsoft.managedidentity/resource.ftl
services/microsoft.storage/resource.ftl
services/resource.ftl

This PR addresses the new OutputMapping handling that is established in the gen3 repo by codeontap/gen3#1021

Implemented latest changes for OutputMappings

---

deploymentframeworks/arm/output.ftl
masterData.ftl
services/resource.ftl

This PR Addresses a number of syntax errors in the core plugin framework for Azure.

Corrected a number of syntax errors in the core plugin framework.

---

components/s3/setup.ftl
deploymentframeworks/arm/output.ftl
services/resource.ftl

This PR Addresses the following:
- As the Storage component is the first Azure plugin component developed, a number of core functions and macros that could not be tested until now required small syntax corrections.
- Final draft of the Storage Component is implemented here. Because both the plugin-core functions and the Storage component had to be tested simultaneously, the Component has reduced features to allow for simplified troubleshooting. Now that the testing of core functionality has been successful the component can be fleshed out to have all features.

Initial Component Template Pass

---

components/s3/setup.ftl
deploymentframeworks/arm/output.ftl
services/resource.ftl

merged formatAzureResourceReference function with getReference to bring it more into alignment with the patterns established by the aws provider.

Refactor - Merge two functions that retrieve resource values.

---

components/network/setup.ftl
components/network/state.ftl
services/microsoft.network/resource.ftl

Implements and Closes: #25 
This PR adds the Network component to the Azure provider plugin. With a CMDB already in place the Network component can be tested with the following:
```
${GENERATION_DIR}/createTemplate.sh -l segment -u vpc -r <azure-region> -p azure -f arm 
${GENERATION_DIR}/manageDeployment.sh -l segment -s resourceGroup -r <azure-region> -u vpc -n <desired-deployment-name>
```

Feature - Network Component

---

services/microsoft.insights/id.ftl
services/microsoft.insights/resource.ftl
services/service.ftl

In preparation for codeontap/gen3-azure#27 this PR incorporates the microsoft.insights service > autoScaleSettings resource.

Implementing autoscale settings.

---

services/microsoft.compute/id.ftl
services/microsoft.compute/resource.ftl
services/microsoft.network/resource.ftl

In preparation for codeontap/gen3-azure#27 this PR introduces the VirtualMachineScaleSets resource.

Implementing VM ScaleSets Resource 

---

inputsources/shared/masterdata.ftl

Updating Azure provider with the latest in processing external resources from codeontap/gen3#1102

Add External Tier

---

components/baseline/setup.ftl

corrected use of STACK_OPERATIONS variable to DEPLOYMENT_OPERATIONS as is Azure convention.

Corrected Variable call.

---

components/baseline/setup.ftl
components/gateway/setup.ftl
components/network/setup.ftl
components/s3/setup.ftl

Aligns the gen3-azure plugin with https://github.com/codeontap/gen3/pull/1136

<refactor> genplan dynamic loading

---

services/microsoft.network.frontdoor/id.ftl
services/microsoft.network.frontdoor/resource.ftl
services/service.ftl

Implements additional resources for codeontap/gen3-azure#59
New Resources:
- microsoft.network/frontDoors
- microsoft.network/FrontDoorWebApplicationFirewallPolicies

added resources frontDoor + frontDoorWAFPolicy

---

utility.sh

Contributes towards #60 
Created utility bash functions for epilogue/prologue scripts to be able to interact with Azure Blob Storage - specifically for a SPA to have the functions it requires to maintain content.

created blob storage util functions to be consumed by SPA

---

components/baseline/setup.ftl
components/baseline/state.ftl
components/bastion/setup.ftl
deploymentframeworks/arm/output.ftl
services/microsoft.keyvault/id.ftl
services/microsoft.keyvault/resource.ftl
services/microsoft.resources/resource.ftl
services/resource.ftl

Implementing a number of functions to allow the creation of ARM template parameters, to address the requirement for them in codeontap/gen3-azure#72
Also includes the functions to create Deployment resources, which allow deployment-scoped resources which will be important for User accounts in the future.

Feature keyvault reference

---

services/resource.ftl

Some resources such as the Azure FrontDoor contain sub-objects that are not stand-alone resources (they cannot be created through a different resource type) however they receive their own ObjectId. This ObjectId is then referenced by other resources.
This PR introduces a new function called ```getSubReference()``` that formats a specific call to getReference that will allow for a type of <provider>/<resource-type>/<child-object-reference>/<grandchild-object-reference> with name segments for all of them. 
The example below shows a reference to the resource "FrontDoor", and its child object "frontendEndpoints" which can be created through this function.
```json
{
"id": "[resourceId('Microsoft.Network/frontDoors/frontendEndpoints', 'frontDoorName', 'frontendEndpointName)]"
}
```
which …

created new macro for referencing objectId's that are not the resourceId

---

services/microsoft.web/id.ftl
services/microsoft.web/resource.ftl
services/service.ftl

Contributes to #63 
* Azure Functions can be implemented through the "sites" ARM resource type.
* Azure App Service Plans can be implemented through the "serverfarms" resource type.
Though Azure functions do have their own resource type, implementing the "sites" resource will provide overlap with other resource implementations required down the track. It is also the established implementation method used amongst all of the Microsoft documentation (rather than the Azure Functions resource).

App Service & Sites resources

---

components/baseline/state.ftl
components/cdn/id.ftl
components/cdn/setup.ftl
components/cdn/state.ftl
components/spa/state.ftl
inputsources/shared/masterdata.ftl
services/microsoft.network.frontdoor/id.ftl
services/microsoft.network.frontdoor/resource.ftl
services/resource.ftl
utility.sh

Implements & Closes #59 
Implements & Closes #60 
This PR implements a new component - CDN. Within Azure this corresponds to the Azure Front Door resource with an associated Web Application Firewall Policy.
* Rules for the WAF can be either "Managed" or "Custom". Currently, CodeOnTap contains the definitions to help mitigate against the for the OWASP "Top 10" Web Application Vulnerability list. In Azure, Microsoft maintain a definition for this and publish it under the "Managed" rules type. This implementation of the CDN makes use of these managed rule sets instead of implementing them based on their CodeOnTap definition. At a later stage this will be revisited to ensure both options can be utilised.
* Quite a number of the resource properties for both FrontDoor and WAF that were listed …

Component - CDN

---

inputsources/shared/masterdata.ftl

This PR includes all of the current standard Azure regions into the Azure provider at the minimum level. 
Note: Future PR's will implement additional network endpoints, this PR is just ensuring templates can be created with existing components for any region.

Feature - Regions

---

services/microsoft.network.frontdoor/resource.ftl
services/microsoft.web/resource.ftl

This refactor applies the ```numberAttributeIfContent()``` function across the provider setup files, to improve the clarity of intent for each attribute.

Refactor - Number Attributes

---

components/spa/state.ftl

Minor fix to correct the way that the SPA Port attributes retrieve their values from the solution.

Fix - SPA Port Attributes

---

components/baseline/setup.ftl
components/baseline/state.ftl
components/cdn/setup.ftl
components/lambda/id.ftl
components/lambda/setup.ftl
components/lambda/state.ftl
components/spa/setup.ftl
components/sqs/setup.ftl
deploymentframeworks/arm/output.ftl
inputsources/mock/blueprint.ftl
inputsources/shared/masterdata.ftl
services/microsoft.storage/resource.ftl
services/microsoft.web/id.ftl
services/microsoft.web/resource.ftl
services/resource.ftl
utility.sh

Contributes to and Closes #63 
This PR implements the Lambda component to the Azure provider.
It also includes:
* new function for formatting an ARM reference function to a Storage Account connection string.
* fixes ```getExistingReference()``` so its finding existing outputs.
* implements WebAppRunTime objects based on solution.RunTime for easy re-use across webapps.

New Component - Lambda

---

deploymentframeworks/arm/output.ftl

Updating ARM output suffix definition as per codeontap/gen3#1075 
@roleyfoley please merge when your original PR is implemented.

refactored arm outputs to meet the new structure in codoentap/gen3#1075

---

services/microsoft.authorization/policy.ftl
services/microsoft.authorization/resource.ftl

Updated so that userRoles is now just for builtInRules

Update - userRoles

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

<feature> Github templates

---

azure/components/adaptor/id.ftl
azure/components/adaptor/setup.ftl
azure/components/adaptor/state.ftl

Implements the idea of an Adaptor component
covered in hamlet-io/engine#1292
Corresponding changes: hamlet-io/engine#1298
Local testing

Feature - New Component - Adaptor

---

azure/components/lambda/state.ftl
azure/components/userpool/id.ftl
azure/components/userpool/setup.ftl
azure/components/userpool/state.ftl
azure/inputsources/shared/masterdata.ftl
azure/services/microsoft.aad.appregistration/id.ftl
azure/services/microsoft.aad.appregistration/resource.ftl
azure/services/microsoft.web/resource.ftl
azure/services/service.ftl

Implements the hamlet component "Userpools" for the Azure provider.
Azure does not have a concept of userpools as other providers (AWS) has. In order to perform any functions within Azure, you first have to have Azure Active Directory (AAD) which replaces much of the purpose of userpools. However, the two subcomponents of userpools - Authentication Provider and Client - have corresponding actions within Azure AD. For the client subcomponent this corresponds with an Azure AD App Registration.
An App Registration is currently not supported within Azure Resource Manager. Due to this, this component will not output a template, but a shell script that implements the desired App Registration.
Note: this Component is to be considered the MVP stage. Additional attribute support for the remaining …

Feature - New Component - Userpools

---

azure/inputsources/shared/masterdata.ftl

Engine Plugins will not load any component configuration unless a valid placement profile is present. This PR implements a default placement profile for Azure, ensuring the components can always be found and implemented.
The [provider.ftl (line 346)](https://github.com/hamlet-io/engine/blob/c21b49e890ec2faf168b77bf7a26cea84230f8e1/engine/provider.ftl#L341) file in the hamlet engine checks specifically for the placementProfile privider attribute.
local testing

added default placement profile

---

azure/components/baseline/setup.ftl

Allow for a CMDB Setting to specify the Object Id of an Administrators group that should be setup with KeyVault view access during baseline component creation/deployment.
Contributes to #120 
Whilst this does not implement the creation of a new administrators account, it does allow for specifying an existing one in CMDB settings. Ultimately both should be supported but this is an improvement on using pseudo-stacks.
Local development, template generation and deployment.

Refactor - Enable AzureAdminstratorsGroup to be a configuration setting.

---

azure/components/db/id.ftl
azure/components/db/setup.ftl
azure/components/db/state.ftl
azure/inputsources/shared/masterdata.ftl
azure/services/microsoft.dbforpostgresql/resource.ftl
azure/services/microsoft.keyvault/id.ftl
azure/services/resource.ftl
azure/utility.sh

Implements the "db" component in its MVP form. Additional engine types and features will be added in future updates. Current form supports the "postgres" DB engine type.
#29 

<Feature> - Component - db

---

azure/components/userpool/setup.ftl

Userpool bash script to output the app-registration to a temp file before reading it with jq.
The userpool bash script output currently didn't parse json correctly with jq. This prevented the certificate generation portion of the script from working.
Local generation and deployment.

Fix - Userpool ObjectId Assignment

---

azure/components/baseline/setup.ftl
azure/components/baseline/state.ftl

The baseline component should take care of the creation of all registries inside of the storage account.
Currently these have been manually created, which is not necessary.
Locally tested and deployed.

Feature - Registries in Baseline

---

azure/references/SkuProfile/id.ftl

Moving getSkuProfiles function from shared provider to Azure plugin.
This was briefly in the Shared provider whilst another matter was handled, now it belongs in the azure provider.
Not tested, new functionality to be tested alongside other PRs.

add getskuprofile

---

azure/components/db/setup.ftl

DB Passwords in azure should always have both alphabetic and numeric characters.
Contributes to #29 
Ran into an intermittent issue deploying a DB component
Generated and deployed templates.

Fix - DB Password Gen

---

azure/components/cdn/setup.ftl
azure/services/microsoft.network.frontdoor/resource.ftl

Updates the CDN host header to match the backend name ("address").
**Note:** Typically I would not swap around the function parameter order like this but given this was only used in one place and its going to be a requirement almost every time I thought I'd adjust it to a better place now whilst I have the chance.
For SPA's hosted in a Storage Account, this is mandatory.

Fix - CDN Backend Host Header

---

azure/components/apigateway/state.ftl
azure/components/cdn/state.ftl
azure/components/userpool/setup.ftl

Updates the userpool component configuration so that it correctly evaluates linked component attributes - particularly when it comes to the externalservice component.
A userpool client needs to know about the various URLS that it should whitelist upon its creation. Most commonly this will either be from an LB or CDN Route subcomponents via the externalservice [link-indirection process](https://github.com/hamlet-io/engine/pull/1287). This change allows the correct handling of attributes discovered via such links.

Refactor - Userpool/Externalservice Attributes

---

azure/deploymentframeworks/arm/output.ftl
azure/provider.ftl
azure/services/microsoft.resources/resource.ftl

Updates the generated ARM template and parameter files to the latest supported schema (which is also the one validated by the ARM language service).
- Restructures the schema values into a global object for ease of future updates.
Closes #126 
Template generation and deployment.

Feature - Update Schemas to 2019-04-01

---

azure/components/userpool/setup.ftl

Remove unused support for LB auth in userpool component.
https://github.com/hamlet-io/engine-plugin-azure/pull/140#discussion_r420573571
small risk fixup - has not been tested. Second pair of eyes should verify this.

Fix - Userpool - Remove Unused LB Auth Support

---

azure/components/baseline/state.ftl
azure/components/cdn/setup.ftl
azure/services/microsoft.storage/resource.ftl

Updates the baseline storage account attributes so that the Web primary endpoint (for static websites) is available when the baseline is linked to. This makes it available to the SPA, and subsequently the CDN.
Rather than hardcoding any values, the baseline should list appropriate attributes to make use of linking within hamlet, ensuring that the CDN is always able to configure itself to the correct endpoint address.
Local template generation and deployment

retrieving web primary endpoint

---

azure/deploymentframeworks/arm/output.ftl

Updates outputs to check the correct property to determine if the output should be a string or an object.
Wasn't working as intended.
Local template generation.

Fix - Dictionary Output Type

---

azure/components/baseline/state.ftl

Resolves an issue that prevents attributes from being set if the baseline hasn't yet deployed.
Prevents most templates generating.
Local template generation and deployment, resulting in correct outputs.

Fix - StorageEndpoints Output

---

azure/components/computecluster/setup.ftl
azure/inputsources/shared/masterdata.ftl
azure/services/microsoft.compute/resource.ftl

Set AutoUpgradeOnMinorUpdate to true on computecluster bootstrap config.
This bootstrap profile involves package deployment, so should run every time.
Template generation and deployment with desired outcome.

Refactor - ComputeCluster AutoUpgrade

---

azure/components/db/setup.ftl

Corrects a spacing issue with a generated bash script.
Spacing error introduced a bug where the correct function could not be found.
Template generation and deployment.

Fix - Spacing in DB Prologue

---

azure/components/baseline/state.ftl
azure/components/cdn/setup.ftl
azure/services/microsoft.network.frontdoor/resource.ftl

Fixed an erroneous pluralisation and ensured backend pool host headers match the address if not explicitly defined.
Pluralisation was incorrect. Host Headers for an SPA must match the pool address.
Template generation and successful deployment.

Fix - CDN Endpoint(s)

---

azure/components/cdn/setup.ftl
azure/components/lambda/setup.ftl
azure/components/spa/setup.ftl
azure/components/spa/state.ftl
azure/services/microsoft.storage/resource.ftl
azure/services/microsoft.web/resource.ftl
azure/utility.sh

- Corrects expected name of the zip file to match the function.
- Allows function deployment seperate to that of the one it retrieves the staged files from.
- Update blob sync utility function authentication method to use the connection string rather than the logged in user account.
- Enable fragment loading on SPA, to generate a .config.
- Linux function app deployments must be made to a unique resource group.
- Names for packages should be more specific than the product name.
- Blob sync auth method as logged in user did not have blob list authorization and thus no copy would occur. We already have sufficient cli args available to retrieve the connection string, so using that is preferred anyhow.
- .config file is required to point the SPA at the right userpoolclient.
Local template …

Fix - Multiple Components Fix

---

azure/components/baseline/state.ftl
azure/components/lambda/setup.ftl
azure/components/sqs/state.ftl
azure/services/microsoft.storage/resource.ftl
azure/services/microsoft.web/resource.ftl

Add fragment support for lambdas.
Lambdas need to be able to pull in appSettings from the CMDB

Fix - Lambda Fragments

---

azure/components/apigateway/setup.ftl
azure/components/apigateway/state.ftl
azure/components/db/setup.ftl
azure/components/id.ftl
azure/services/microsoft.apimanagement/resource.ftl
azure/services/resource.ftl

- Removed 2 unused resources from the API Gateway component
- Corrected the FQDN to use when not using a certificate.
- Add support for BasePathBehaviour in the solution.
- Removed the SERVICE_PRINCIPAL attribute and output from the API Gateway component.
- Disabled a debug on the DB component.
- Tidy up
- When APIGateway component isn't using a certificate, the FQDN to use is that of the Azure API Management Service (the "service" resource in state.ftl), not  the API resource itself.
- Hamlet users should be able to control if there are any basePath suffix's or not.
- The SERVICE_PRINCIPAL attribute of any given resource isn't ideal as an output ever, as it may or may not exist and outputs are defined before that logic is run. Instead, this value can be obtained during deployment with a …

Refactor - API Gateway Component

---

azure/components/baseline/state.ftl
azure/components/bastion/setup.ftl
azure/components/computecluster/setup.ftl
azure/components/db/state.ftl
azure/components/s3/state.ftl
azure/inputsources/shared/masterdata.ftl
azure/services/microsoft.apimanagement/resource.ftl
azure/services/microsoft.dbforpostgresql/resource.ftl
azure/services/microsoft.keyvault/resource.ftl
azure/services/microsoft.storage/resource.ftl

1. Moves the timestamp VM ScaleSet attribute to Settings instead of Protected Settings
2. Update function that formats connection string ARM function with the value of the storage account Id, and not just the Id
3. Update s3 Attributes
4. Fix the default storage account config and the linked storage account config
5. Added Bootstraps that will install the barebones required to get going with Azure - the CLI and unzip.
6. Remove unnecessary parameter from `createKeyVaultParameterLookup` macro
7. Removed stray bracket.
8. Implement ability to specify KeyVault "secrets" in the solution
9. Gather linked DB information and inject as environment variables alongside secrets.
1. Timestamp cannot deploy repeatedly as a protected setting, but must update each deployment (it is what tells an …

Fix - ComputeCluster

---

azure/components/baseline/setup.ftl

Allow a comma separated list of keyVaultAdmins to be used in the key vault policy
When deploying with service principals and an admin group the service principal might not be part of the admin group. This allows for list of admins to be set.
Tested locally with template generation

feat(baseline): allow multiple keyVaultAdmins

---

azure/components/db/setup.ftl
azure/services/microsoft.apimanagement/resource.ftl

Allow for the DB Component Vnet Rule to be created when the subnet doesn't currently have the Service Endpoint "Microsoft.Sql" enabled.
This currently fails a deployment at deployment time.
Local template generation.

Fix DB Vnet Rule

---

azure/components/baseline/setup.ftl
azure/components/lb/setup.ftl
azure/inputsources/mock/definition.ftl
azure/services/microsoft.apimanagement/resource.ftl
azuretest/provider.ftl
azuretest/scenarios/adaptor.ftl
azuretest/scenarios/apigateway.ftl
azuretest/scenarios/baseline.ftl
azuretest/scenarios/bastion.ftl
azuretest/scenarios/cdn.ftl
azuretest/scenarios/computecluster.ftl
azuretest/scenarios/db.ftl
azuretest/scenarios/gateway.ftl
azuretest/scenarios/lambda.ftl
azuretest/scenarios/lb.ftl
azuretest/scenarios/network.ftl
azuretest/scenarios/s3.ftl
azuretest/scenarios/spa.ftl
azuretest/scenarios/sqs.ftl
azuretest/scenarios/userpool.ftl
test/run_azure_template_tests.sh

Update of the provider testcases, including:
- baseline component - allow an empty value to be the result of looking up the Azure Administrator setting. This was turned up as an issue during testing.
- add a component testing base for `network` and `baseline` components.
- update test shell script with directory navigation that ends up back in the directory it started in.
- Continuing to rollout component testing updates.
- Running the shell script over and over was creating subdirs every time.
- #70 
Local test generation and execution.
- [] I have added tests to cover my changes.

Feat more azure testcases

---

Jenkinsfile
test/run_azure_template_tests.sh

Updates the Azure test template generation script to use the new unit list format based on the provided management contract format. Now that we know the deployment group that all units belong to also remove the `|| true` return on template generations so we know when template generation fails
The introduction of the management contract provides better understanding of the units available in a deployment. This allows us to generate test templates in a more  efficient way. It should also allow us to catch problems when they occur at any stage in template generation
- Depends on -  https://github.com/hamlet-io/executor-bash/pull/87

refactor: use management contract for testing

---

Jenkinsfile

Add a build timeout to the Jenkins pipeline
When an error occurs, the build may run indefinitely, wasting resources.
Has not yet been tested.

Fix - Jenkins Timeout

---

azure/components/adaptor/state.ftl
azure/components/lb/state.ftl
azure/deploymentframeworks/arm/output.ftl
azure/inputsources/composite/stackoutput.ftl
azure/services/resource.ftl

Change all usage of "COT" to "Hamlet".
Tidy up activity to align messaging with renaming of the framework.
Local deployment
Should only be merged AFTER

refactor: switch COT to Hamlet

---

azure/components/network/state.ftl

Align with layer configuration and data introduced as part of https://github.com/hamlet-io/engine/pull/1448 
Aligns with the composite data structure format
Tested locally

refactor: align with layerdata configuration

---

Jenkinsfile

* disable test suite temporarily in CI
Due to issues experienced by all in #216 the test suite is being
temporarily disabled whilst it is brought into alignment with the AWS
provider, which is working correctly as intended.
n/a

fix(ci): disable test suite

---

Jenkinsfile
test/run_azure_template_tests.sh

- Updates the Azure plugin testing to include junit reports 
- Uses the hamlet cli for all commands 
- Fixes the docker build trigger to only run on master changes
Align testing and provide better response
Testing as part of PR

feat(ci): Align azure testing with plugins and include junit

---

azure/components/network/setup.ftl
azure/components/network/state.ftl
azure/inputsources/shared/masterdata.ftl
azure/services/microsoft.network/id.ftl
azure/services/microsoft.network/resource.ftl
azuretest/modules/cdn/module.ftl
azuretest/modules/computecluster/module.ftl
azuretest/modules/network/module.ftl

- Realigns Network component FlowLogs with Shared provider definitions
- Fixes a number of incorrect attributes in the provider master data and modules
The Azure implementation of changes made in hamlet-io/engine#1548
Listed as breaking change as this will likely cause changes to existing deployments.
- hamlet-io/engine#1548
- Closes https://github.com/hamlet-io/engine-plugin-azure/issues/222
Locally tested alongside corresponding engine PR.

Fix - Invalid Module and Masterdata structures

---

Jenkinsfile

minor fix to pipeline syntax 
pipeline was broken 
Will test as part of PR

fix(cicd): jenkins pipeline structure

---

azure/components/containerhost/id.ftl
azure/components/db/id.ftl

Minor update to ensure consistency of attribute parameters across Hamlet.
Consistency.
n/a

chore: realign attribute parameter case

---

azure/inputsources/shared/masterdata.ftl

Removes, corrects or adds otherwise invalid masterdata configuration.
Validating this data with hamlet-io/engine#1548 brought these to light
Validation in hamlet-io/engine#1548

Fix: Validated Masterdata

---

azure/components/baseline/setup.ftl
azure/components/baseline/state.ftl
azure/components/bastion/setup.ftl
azure/components/db/setup.ftl
azure/deploymentframeworks/arm/output.ftl
azure/services/microsoft.keyvault/id.ftl
azure/services/microsoft.keyvault/resource.ftl

- new ARM resource for KeyVault Key
- update baseline `cmk` to use new Key resource
- fix regex if-statements when querying for existence of secrets (across the board)
- add checks for existing secrets prior to deletion (previously only for creation)
- remove CMK resource type
- remove key vault purge protection (creating then deleting adds significant effort involved in going anywhere from this state)
- various small tidy ups (on resource impacted by greater changes only)
Baseline epilogue script was failing to upload keys. This would prevent any component that expected them from deploying.
Local generation and subsequent deployment

Fix - Baseline Key deployments

---

README.md

Adds a README to the repository covering basic usage and directs users to the docs site
Consistency across the Hamlet Deploy ecosystem
N/a

feat: add readme to repository

---

README.md

Remove contribute section from README
It's going to be added to the GitHub repo to cover all of them
n/a

fixup: remove contributing section

---

test/run_azure_template_tests.sh

Align with the cli changes introduced in https://github.com/hamlet-io/executor-python/pull/89
Testing broken 
Will use CI Testing

fix: test args for hamlet cmd

---

azure/deploymentframeworks/arm/output.ftl

Updates the output handler to support output generation in the engine
Azure implementation of https://github.com/hamlet-io/engine/pull/1583 
-

refactor: output handling in engine

---

Jenkinsfile

Install the latest version of hamlet on the setup of job
Removes the waiting period required for containers to build and provides more reliable testing results
Will test in Jenkins

feat(cd): setup latest hamlet on each run

---

CHANGELOG.md
package.json

Add  release notes for version 8.0.1 of hamlet
Shows changes that have been made
Tested locally

chore: 8.0.1 release notes

---

azure/inputseeders/azure/id.ftl

A minor change to invoke the correct inputseeder config pipeline function
Current spelling of this function does not exist, causing the provider to fail when used.
Local template generation

fix: invoke correct config pipeline function

---

azure/components/apigateway/setup.ftl
azuretest/modules/apigateway/module.ftl

Adds support for sourcing the openapi specification from different places including the none option which is useful for module deployments
Easier integration with hamlet for apigateways and easier support for modules
Tested locally

feat(apigateway): adds image source support

---

azure/deploymentframeworks/arm/output.ftl

Updates the arm output to align with extension of the output properties for different output types
Aligns azure provider with Aligns hamlet-io/engine#1639
tested locally

refactor: update output properties with new config

---

azure/components/baseline/id.ftl
azure/components/spa/id.ftl

Allows for users to modify the storage profile for the spa component
Allows for users to control the storage profile used on their components
Tested locally

feat: add storage profile configuration for spa

---

azure/components/apigateway/setup.ftl

Adds support for adding or modifying the openapi specification of an apigateway through an extension.
Makes it easy to specific basic specifications via fragments or to modify them if required 
- None
- None
- None

feat(apigateway): openapi specification extension

---

CHANGELOG.md

Updates the changelog for the latest release 8.1.2 
Shows what we have been doing 
- None
- None
- None

chore: changelog 8.1.2

---

.dockerignore
.github/workflows/package.yml
Dockerfile

Adds support for creating a docker based image of the repo for use with the hamlet setup process
To make it easy to install and setup hamlet ( hamlet-io/architectural-decision-log#11 )
- None
- None
- None

feat: support for docker based packaging

---

.github/workflows/changelog.yml
.github/workflows/package.yml
.github/workflows/testing.yml
.gitignore

Updates the pipelines to align with testing and operational usage
- Make the changelog PR a draft and mark the unreleased changes as latest. This allows us to tag the release with a change log and not have to move it
- Only run packaging if the testing passes
- Add support for writing build details into the source
Makes the CI process cleaner and more robust
Tested on AWS provider repo
- None
- None
- None

refactor(ci): updates from testing and ops

---

.dockerignore

Adds the .git directory to the dockerignore list
Reduces the size of the packages used for the engine. The build information is now included in the .hamlet dir 
tested locally
- None
- None
- None

refactor(ci): remove git dir from docker

---

.github/workflows/package.yml

fixes the pr trigger syntax for the package workflow 
Make sure package workflows work during PRs
Will be tested with PR
- None
- None
- None

fix(ci): update package trigger pr syntax

---

.github/workflows/release.yml
README.md

- removes dos2unix from cicd pipelines
- reference install guide for recommended setup process
Removes the installation of extra packages
- None
- None
- None

refactor: remove dos2unix usage

---

.github/workflows/release.yml
azure/components/apigateway/setup.ftl
azure/components/baseline/setup.ftl
azure/components/baseline/state.ftl
azure/components/bastion/setup.ftl
azure/components/cdn/setup.ftl
azure/components/computecluster/setup.ftl
azure/components/containerhost/setup.ftl
azure/components/db/setup.ftl
azure/components/gateway/setup.ftl
azure/components/gateway/state.ftl
azure/components/lambda/setup.ftl
azure/components/lb/setup.ftl
azure/components/network/setup.ftl
azure/components/s3/setup.ftl
azure/components/spa/setup.ftl
azure/deploymentframeworks/arm/output.ftl
azure/services/microsoft.network/resource.ftl

Replace the use of global variables from `setContext()` with accessor functions for the same information.
This is in preparation for full district support, where all config and state access needs to be via the input state.
- https://github.com/hamlet-io/engine/pull/1821
- https://github.com/hamlet-io/engine/pull/1830
- None
- None

refactor: setContext wrapper functions (1)

---

azure/components/baseline/setup.ftl

- Removes explicit creation of web container to allow for subcomponent to handle creation
- Clean up baseline data role setup
Was causing duplicate resources in templates 
Tested locally
- None
- None
- None

fix: remove extra container creation

---

azure/components/db/setup.ftl
azure/components/db/state.ftl

- Updates the database credential configuration to align with the recent changes to core and aws
Template generation failing
Tested locally using test suite
- None
- None
- None

fix: update database credentials setup

---

azure/services/microsoft.web/resource.ftl
azuretest/modules/lambda/module.ftl

- Aligns azure lambda runtimes with the updates made for latest code versions
- Fixes a bug with runtime errors to ensure they are working as expected
Template testing failing to run for tram releases
Tested locally
- None
- None
- None

fix(lambda): align runtimes with latest updates

---

.github/workflows/release.yml
engine.ini

- Adds a local engine definition file which can be used for testing the provider locally
Fixes issues with testing where the environment variables used to define the plugin were overridden by the hamlet cli. 
- None
- None
- None

refactor: use local engine for testing

---

azuretest/inputseeders/azuretest/id.ftl
azuretest/inputsources/shared/blueprint.ftl

- Solution Layer has been removed so need to ensure that test modules are loaded
Align with the changes in https://github.com/hamlet-io/engine/pull/1971 which removes the Solution layer
Tested locally
- None
- None
- None

refactor: move test module loading to product layer

---

azure/components/baseline/setup.ftl
azure/components/cdn/setup.ftl
azure/components/externalnetwork/setup.ftl
azure/components/gateway/setup.ftl
azure/components/lambda/setup.ftl
azure/components/lb/setup.ftl
azure/components/network/setup.ftl
azure/components/userpool/setup.ftl

- Checks the state of subcccurences to make sure they should be deployed
Follow the inbuilt attribute which was being ignored when generating deployments
Tested locally
- None
- None
- None

refactor: enabled handling for suboccurrences

---

azure/components/lb/setup.ftl
azure/components/lb/state.ftl

Use standard fatal error for invalid port mapping
Part of https://github.com/hamlet-io/engine/issues/1685
Locally
- None
- None
- None

fix(lb): standard error for invalid port mapping

---

azure/components/baseline/id.ftl
azure/components/s3/id.ftl

- Update overrides applied on components to use the AttributeSets introduced for base attribute sets
https://github.com/hamlet-io/engine/pull/2034 
tested locally
- https://github.com/hamlet-io/engine/pull/2034
- None
- None

refactor: use base level attribute sets

---

.github/workflows/changelog.yml
.github/workflows/release.yml

- Disable changelogs on tags
- Use shared workflow for building engine images
Makes it easier to maintain github actions across different parts of hamlet that produce engine parts
- None
- None
- None

refactor: standardise github workflows

---

.github/workflows/release.yml

image build weren't updating the edge tag
- Current shared workflow wasn't tagging images properly
- None
- None
- None

fix(ci): update to latest shared workflows

---

.github/workflows/changelog.yml
.github/workflows/release.yml

Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None

chore: update github action pipelines
